First pass at adding clang-tidy to circleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -52,8 +52,17 @@ jobs:
       - <<: *install_deps
       - run: pip3 install --upgrade -r util/requirements3.txt
       - run: git fetch origin && STYLIZE_DIFFBASE=origin/staging make checkstyle-lines
+      - run: |
+          STYLIZE_DIFFBASE=origin/staging make checktidy-lines
+          cat /tmp/checktidy.patch | python3 util/clang-tidy-to-junit.py > /tmp/clang_tidy.xml
+          if [[ -n $(grep '[^[:space:]]' /tmp/checktidy.patch) ]]; then
+            echo "****************************** clang-tidy errors *******************************"
+            exit 1
+          fi
       - store_artifacts:
           path: /tmp/clean.patch
+      - store_test_results:
+          path: /tmp/clang_tidy.xml
 
   gen-docs:
     <<: *dir
